name: Making my Data Science Projects End to End

on: 
  push:
    branches: ["main"]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“ Dragging code from github to this virtual environment
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"  
    
    - name: ğŸ“¦ Install dependencies
      run: pip install -r requirements.txt    
        
    - name: ğŸ® Unit Testing
      run:  pytest -v ./testing/app_test.py

    - name: ğŸš€ Inference time babyyy
      run: uvicorn src.inference:app --host 0.0.0.0 --port 8000 